color_palettes:
- name: greyscale
  color_vals:
  - value: 0.0
    red: 0
    green: 0
    blue: 0
  - value: 1
    red: 255
    green: 255
    blue: 255
- color_vals:
    - red: 0
      green: 18
      blue: 25
      value: 0.
    - red: 0
      green: 18
      blue: 25
      value: 0.1
    - red: 20
      green: 33
      blue: 61
      value: 0.5
    - red: 252
      green: 163
      blue: 17
      value: 0.8
    - red: 229
      green: 229
      blue: 229
      value: 0.9
    - red: 255
      green: 255
      blue: 255
      value: 0.95
    - red: 0
      green: 0
      blue: 0
      value: 1.0
  name: electric
named_points:
  - name: capillary
    point:
      re: -0.0452407411
      im: 0.9868162204352258
    zoom: 51200000
  - name: chloro-zoom
    point:
      re: 0.281717921930775
      im: 0.5771052841488505
    zoom: 102400000000
  - name: chlorophyll
    point:
      re: 0.281717921930775
      im: 0.5771052841488505
    zoom: 25600000000
  - name: circle
    point:
      re: 0.432539867562512
      im: 0.226118675951765
    zoom: 25000000000000
  - name: divergence
    point:
      re: 0.2549870375144766
      im: -0.0005679790528465
    zoom: 200000
  - name: doubletentacle
    point:
      re: -0.745428
      im: 0.113009
    zoom: 400000
  - name: knife
    point:
      re: -1.25066
      im: 0.02012
    zoom: 75000
  - name: spiral
    point:
      re: -0.7771204433106587
      im: 0.1268572387863619
    zoom: 20000
  - name: splotches
    point:
      re: -0.74529
      im: 0.113075
    zoom: 80000
  - name: tendril
    point:
      re: -0.235125
      im: 0.827215
    zoom: 260000
  - name: tentacle
    point:
      re: -0.7453
      im: 0.1127
    zoom: 10000
  - name: tilt
    point:
      re: -0.16
      im: 1.035
    zoom: 900
  - name: tilt-zoom-out
    point:
      re: -0.16
      im: 1.035
    zoom: 700
  - name: void
    point:
      re: -1.25066
      im: 0.02012
    zoom: 200000
