[workspace]

members = ["mandelbrust", "mandelbrust-gif", "mandelbrust-cli"]

resolver = "2"

[workspace.dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_derive = "1.0.152"
confy = "0.6.1"
image = "0.25.2"
anyhow = "1.0.87"
